"""add output storage keys

Revision ID: 57a516cd1d0f
Revises: da51603d6024
Create Date: 2026-07-24 02:18:47.916853
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '57a516cd1d0f'
down_revision: Union[str, None] = 'da51603d6024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_mp3_key', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output_m4b_key', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('output_m4b_key')
        batch_op.drop_column('output_mp3_key')

    # ### end Alembic commands ###
