"""rate buckets

Revision ID: 9e8fdbef29e0
Revises: a696a1a2ecde
Create Date: 2026-07-24 02:40:40.965595
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e8fdbef29e0'
down_revision: Union[str, None] = 'a696a1a2ecde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_buckets',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('window_start', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'window_start')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rate_buckets')
    # ### end Alembic commands ###
