"""usage events and org quota columns

Revision ID: a696a1a2ecde
Revises: 57a516cd1d0f
Create Date: 2026-07-24 02:38:34.637495
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy as sa

revision: str = 'a696a1a2ecde'
down_revision: Union[str, None] = '57a516cd1d0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('characters', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_usage_org_period', ['organization_id', 'period'], unique=False)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_char_quota', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('qc_policy', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('retention_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_column('retention_days')
        batch_op.drop_column('qc_policy')
        batch_op.drop_column('monthly_char_quota')

    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_org_period')
        batch_op.drop_index(batch_op.f('ix_usage_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_job_id'))

    op.drop_table('usage_events')
    # ### end Alembic commands ###
