"""initial schema

Revision ID: da51603d6024
Revises: 
Create Date: 2026-07-24 01:24:29.556617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import db.base


revision: str = 'da51603d6024'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('memberships',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('user_id', db.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', db.base.GUID(length=36), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', db.base.GUID(length=36), nullable=False),
    sa.Column('created_by', db.base.GUID(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('organization_id', db.base.GUID(length=36), nullable=False),
    sa.Column('project_id', db.base.GUID(length=36), nullable=False),
    sa.Column('created_by', db.base.GUID(length=36), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('voice_id', sa.String(length=120), nullable=False),
    sa.Column('engine', sa.String(length=30), nullable=False),
    sa.Column('formats', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'canceled', name='jobstatus', native_enum=False, length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('chapters_count', sa.Integer(), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=False),
    sa.Column('cached_chunks', sa.Integer(), nullable=False),
    sa.Column('synthesized_chunks', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('output_mp3', sa.Text(), nullable=True),
    sa.Column('output_m4b', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locked_by', sa.String(length=100), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_claim', ['status', 'available_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('chapter_results',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('job_id', db.base.GUID(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'skipped', 'failed', name='chapterstatus', native_enum=False, length=20), nullable=False),
    sa.Column('cached_chunks', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('loudness_dbfs', sa.Float(), nullable=True),
    sa.Column('peak_dbfs', sa.Float(), nullable=True),
    sa.Column('silence_ratio', sa.Float(), nullable=True),
    sa.Column('clipping', sa.Boolean(), nullable=True),
    sa.Column('qc_passed', sa.Boolean(), nullable=True),
    sa.Column('qc_issues', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'index', name='uq_job_chapter_index')
    )
    with op.batch_alter_table('chapter_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_results_job_id'), ['job_id'], unique=False)

    op.create_table('job_attempts',
    sa.Column('id', db.base.GUID(length=36), nullable=False),
    sa.Column('job_id', db.base.GUID(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_attempts_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_attempts_job_id'))

    op.drop_table('job_attempts')
    with op.batch_alter_table('chapter_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_results_job_id'))

    op.drop_table('chapter_results')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_organization_id'))
        batch_op.drop_index('ix_jobs_claim')

    op.drop_table('jobs')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
